# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49a69f5655c0b17f16b78a67561e2a81fd79509f7259a4861ead5e0035aa5a07478e2455593adbb26f836697ef19fb30e750350d2b1c593cf16af363cb6dee39

test:
  secret_key_base: 31d0b344f44fe4ea64d134d6612f6cd770c9f2eb16bbc3cf2e73c27964433bfbcf84df3401a1eaf9220a9613a0c7e23f3aac09c6ff8342e1277e819c0a93194b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
